name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PDM
        run: pip install pdm

      - name: Ensure deps
        run: |
          pdm config pypi.pytorch.url https://download.pytorch.org/whl/cpu
          pdm install

      - name: Black
        id: black
        run: |
          pdm run black GUNTAM/
          if ! git diff --quiet; then
            git diff > black.patch
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Fail on formating
        if: steps.black.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: black-formatting-patch
          path: black.patch
      
      - name: Flake8
        run: pdm run flake8        
      
      - name: Fail on black reformating
        if: steps.black.outputs.changed == 'true'
        run: exit 1
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PDM
        run: pip install pdm

      - name: Ensure deps
        run: |
          pdm config pypi.pytorch.url https://download.pytorch.org/whl/cpu
          pdm install

      - name: Run tests
        run: pdm run pytest --cov=GUNTAM --cov-branch --cov-report= --ignore=tests/test_integration

      - name: Rename coverage data
        run: |
          mv .coverage .coverage.test

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-test
          path: .coverage.test


  Typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PDM
        run: pip install pdm

      - name: Ensure deps
        run: |
          pdm config pypi.pytorch.url https://download.pytorch.org/whl/cpu
          pdm install

      - name: Run mypy
        run: pdm run mypy -p GUNTAM

  integration-test-train:
    runs-on: ubuntu-latest
    needs: [lint, test, Typing]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PDM
        run: pip install pdm

      - name: Ensure deps
        run: |
          pdm config pypi.pytorch.url https://download.pytorch.org/whl/cpu
          pdm install

      - name: Run integration tests
        run: pdm run pytest tests/test_integration/test_integration_train.py --cov=GUNTAM --cov-branch --cov-report=

      - name: Rename coverage data
        run: |
          mv .coverage .coverage.integration_train

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-integration_train
          path: .coverage.integration_train

  integration-test_run:
    runs-on: ubuntu-latest
    needs: [lint, test, Typing]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PDM
        run: pip install pdm

      - name: Ensure deps
        run: |
          pdm config pypi.pytorch.url https://download.pytorch.org/whl/cpu
          pdm install

      - name: Run integration tests
        run: pdm run pytest tests/test_integration/test_seeding_chain.py --cov=GUNTAM --cov-branch --cov-report=

      - name: Rename coverage data
        run: |
          mv .coverage .coverage.integration_chain

      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-integration_chain
          path: .coverage.integration_chain

      
  coverage:
    runs-on: ubuntu-latest
    needs: [test, integration-test]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install PDM
        run: pip install pdm

      - name: Ensure deps
        run: |
          pdm config pypi.pytorch.url https://download.pytorch.org/whl/cpu
          pdm install

      - name: Download coverage data
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: coverage-data
          merge-multiple: true

      - name: Combine coverage
        run: |
          mkdir coverage-combined
          cp coverage-data/.coverage.* coverage-combined/

          cd coverage-combined
          pdm run coverage combine
          pdm run coverage xml -o coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage-combined/coverage.xml
